### ISSUE TITLE
Websocket Issues

### ISSUE THREAD

**Issue by explodatedfaces** [jeastham1993/serverless-cloudflare#1]
https://github.com/jeastham1993/serverless-cloudflare/blame/9733263da6848c4f4237ae1c31caa273fc869e70/src/backend/src/chatroom.rs#L189

After reviewing your code the community at ThePrimeAgen took issue with this line. I'm not sure what the issue was but something about websockets closing or not persisting.

![image](https://github.com/user-attachments/assets/60b49b6d-6f96-4d12-9f7a-261f48539834)

**Comment by Tebarem** [comment]
@jeastham1993 just to clarify. I am learning about cloudflare workers and looking at how we have to do some ugly stuff around cloudflare infra made me uneasy

**Comment by jeastham1993** [comment]
> https://github.com/jeastham1993/serverless-cloudflare/blame/9733263da6848c4f4237ae1c31caa273fc869e70/src/backend/src/chatroom.rs#L189
> 
> After reviewing your code the community at ThePrimeAgen took issue with this line. I'm not sure what the issue was but something about websockets closing or not persisting.
> 
> ![image](https://private-user-images.githubusercontent.com/23347409/383488646-60b49b6d-6f96-4d12-9f7a-261f48539834.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4ODcxMDUsIm5iZiI6MTczMDg4NjgwNSwicGF0aCI6Ii8yMzM0NzQwOS8zODM0ODg2NDYtNjBiNDliNmQtNmY5Ni00ZDEyLTlmN2EtMjYxZjQ4NTM5ODM0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDA5NTMyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4ZTIyMDc3NmVlMTdjNWE0N2M5NmIyM2IxZGU1YjQ5MDNiMGUyZGEzNDY5YTEyNThiZDJjOTQ5YzYwNDMxMjImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.FMq0CJ00dNZu7Rzuhroy0_cuLhoDvT9PUx_rZGJtTxM)

Could you provide more details on what you mean by 'took issue'? The screenshot of struggling with mental illness isn't particularly helpful or relevant to someone learning Rust...

**Comment by Tebarem** [comment]
There is no issue really just seeing and learning how to use workers and cloudflare products in rust
